# 3. 다중 회귀 분석 (Multiple Regression)
* 독립변수가 2개 이상인 회귀분석
* 특성이 1개면 직선형태를 학습함 (y = a * x + b)
* 특성이 2개면 평면을 학습함 (y = a * x1 + b * x2 + c)

## 2-1. 농어 길이와 높이에 따른 무게 예측

### 1) 문제 정의
농어 길이(Length), 높이(Height), 두께(Width)에 따른 무게(Weight) 예측하기

### 2) 데이터 수집
* https://www.kaggle.com/aungpyaeap/fish-market

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

ori_data = pd.read_csv('data/02_fish/fish.csv')
ori_data

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [5]:
data = ori_data[ori_data.Species=='Perch'][['Length2', 'Height', 'Width', 'Weight']]
data.columns = ['Length', 'Height', 'Width', 'Weight']
data

     Length   Height   Width  Weight
72      8.4   2.1120  1.4080     5.9
73     13.7   3.5280  1.9992    32.0
74     15.0   3.8240  2.4320    40.0
75     16.2   4.5924  2.6316    51.5
76     17.4   4.5880  2.9415    70.0
77     18.0   5.2224  3.3216   100.0
78     18.7   5.1992  3.1234    78.0
79     19.0   5.6358  3.0502    80.0
80     19.6   5.1376  3.0368    85.0
81     20.0   5.0820  2.7720    85.0
82     21.0   5.6925  3.5550   110.0
83     21.0   5.9175  3.3075   115.0
84     21.0   5.6925  3.6675   125.0
85     21.3   6.3840  3.5340   130.0
86     22.0   6.1100  3.4075   120.0
87     22.0   5.6400  3.5250   120.0
88     22.0   6.1100  3.5250   130.0
89     22.0   5.8750  3.5250   135.0
90     22.0   5.5225  3.9950   110.0
91     22.5   5.8560  3.6240   130.0
92     22.5   6.7920  3.6240   150.0
93     22.7   5.9532  3.6300   145.0
94     23.0   5.2185  3.6260   150.0
95     23.5   6.2750  3.7250   170.0
96     24.0   7.2930  3.7230   225.0
97     24.0   6.3750  3.8250   145.0
98     24.6   6.7334  4.1658   188.0
99     25.0   6.4395  3.6835   180.0
100    25.6   6.5610  4.2390   197.0
101    26.5   7.1680  4.1440   218.0
102    27.3   8.3230  5.1373   300.0
103    27.5   7.1672  4.3350   260.0
104    27.5   7.0516  4.3350   265.0
105    27.5   7.2828  4.5662   250.0
106    28.0   7.8204  4.2042   250.0
107    28.7   7.5852  4.6354   300.0
108    30.0   7.6156  4.7716   320.0
109    32.8  10.0300  6.0180   514.0
110    34.5  10.2565  6.3875   556.0
111    35.0  11.4884  7.7957   840.0
112    36.5  10.8810  6.8640   685.0
113    36.0  10.6091  6.7408   700.0
114    37.0  10.8350  6.2646   700.0
115    37.0  10.5717  6.3666   690.0
116    39.0  11.1366  7.4934   900.0
117    39.0  11.1366  6.0030   650.0
118    39.0  12.4313  7.3514   820.0
119    40.0  11.9286  7.1064   850.0
120    40.0  11.7300  7.2250   900.0
121    40.0  12.3808  7.4624  1015.0
122    40.0  11.1350  6.6300   820.0
123    42.0  12.8002  6.8684  1100.0
124    43.0  11.9328  7.2772  1000.0
125    43.0  12.5125  7.4165  1100.0
126    43.5  12.6040  8.1420  1000.0
127    44.0  12.4888  7.5958  1000.0

### 3) 데이터 전처리
* 결측치 처리

In [6]:
data.shape

(56, 4)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56 entries, 72 to 127
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Length  56 non-null     float64
 1   Height  56 non-null     float64
 2   Width   56 non-null     float64
 3   Weight  56 non-null     float64
dtypes: float64(4)
memory usage: 2.2 KB

In [8]:
data.isnull().sum()

Length    0
Height    0
Width     0
Weight    0
dtype: int64

### 4) 데이터 탐색
* 상관관계
* 산점도(Scatter Plot) -> 생략

In [10]:
data.corr()

          Length    Height     Width    Weight
Length  1.000000  0.985584  0.974617  0.958656
Height  0.985584  1.000000  0.982943  0.968441
Width   0.974617  0.982943  1.000000  0.963943
Weight  0.958656  0.968441  0.963943  1.000000

### 5) 모델 학습
* 데이터 쪼개기
* 다중회귀 학습
* 다중회귀 예측

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [25]:
# 독립변수 : Length, Height, Width
# 종속변수 : Weight
input_data = data[['Length', 'Height', 'Width']].to_numpy()
target_data = data['Weight'].to_numpy()
input_data.shape, target_data.shape

((56, 3), (56,))

In [26]:
# 훈련 세트와 테스트 세트 나누기
train_input, test_input, train_target, test_target = train_test_split(input_data, target_data, random_state=0)
train_input.shape, test_input.shape, train_target.shape, test_target.shape

((42, 3), (14, 3), (42,), (14,))

In [27]:
lr = LinearRegression()

In [28]:
lr.fit(train_input, train_target)

LinearRegression()

In [29]:
lr.coef_, lr.intercept_

(array([-7.80989989e-02,  8.51699274e+01,  5.92449041e+01]),
 -556.7642765166698)

In [30]:
lr.predict([[50, 15, 10]])

array([1309.32872567])

In [31]:
# Weight = a * Length + b * Height + c * Width + d
-7.80989989e-02 * 50 + 8.51699274e+01 * 15 + 5.92449041e+01 * 10 -556.7642765166698

1309.3287255383302

In [37]:
### 6) 모델 평가
pred = lr.predict(test_input)
pd.DataFrame({'Length': test_input[:,0], 
              'Height': test_input[:,1], 
              'Width': test_input[:,2], 
              'Actual Weight': test_target, 'Predicted Weight': pred})

    Length   Height   Width  Actual Weight  Predicted Weight
0     39.0  11.1366  6.0030          650.0        744.340435
1     27.5   7.2828  4.5662          250.0        331.887629
2     36.5  10.8810  6.8640          685.0        773.776112
3     24.6   6.7334  4.1658          188.0        261.600099
4     21.0   5.9175  3.3075          115.0        141.541210
5     15.0   3.8240  2.4320           40.0        -88.162352
6     27.5   7.0516  4.3350          265.0        298.498920
7     37.0  10.5717  6.3666          690.0        717.925589
8     39.0  12.4313  7.3514          820.0        934.495769
9     27.3   8.3230  5.1373          300.0        454.331772
10    17.4   4.5880  2.9415           70.0          6.905313
11    21.0   5.6925  3.5550          110.0        137.041090
12    25.6   6.5610  4.2390          197.0        251.175431
13    23.0   5.2185  3.6260          150.0        100.720735

In [38]:
lr.score(train_input, train_target)

0.946573874702987

In [39]:
lr.score(test_input, test_target)

0.8974351710978307